name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: ./mkdockerize.sh build

      - name: Test produce
        run: |
          ./mkdockerize.sh produce ./test > test.tgz
          ls -lh test.tgz

      - name: Test serve
        run: |
          cat test.tgz | ./mkdockerize.sh serve &
          sleep 10
          curl -f http://localhost:8000 || (echo "MkDocs did not serve correctly" && exit 1)
